version: 2
jobs:
  one:
   build:
     docker:
      - image: debian:stretch
     steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Mumbai.
  two:
   build:
     docker:
      - image: debian:stretch
     steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Hyd.  
workflows:
 version: 2
   one_and_two:
      jobs:
       - one
       - two
 
