version: 2
jobs:
   one:
   build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Mumbai.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: get the user info
          command: whoami

 two:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, Mumbai.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: get the user info
          command: whoami
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
     
          

